{{- if and .Values.Service.Frontend.HPA.enabled .Values.Service.Frontend.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.Service.Frontend.name }}-hpa
  namespace: {{ .Values.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.Service.Frontend.name }}
  minReplicas: {{ .Values.Service.Frontend.HPA.minReplicas }}
  maxReplicas: {{ .Values.Service.Frontend.HPA.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.Service.Frontend.HPA.cpuUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.Service.Frontend.HPA.memoryUtilization }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 30
          periodSeconds: 60
---
{{- end -}}


{{- if and .Values.Service.Backend.HPA.enabled .Values.Service.Backend.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.Service.Backend.name }}-hpa
  namespace: {{ .Values.Namespace }}
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.Service.Backend.name }}
  minReplicas: {{ .Values.Service.Backend.HPA.minReplicas }}
  maxReplicas: {{ .Values.Service.Backend.HPA.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.Service.Backend.HPA.cpuUtilization }}
    - type: Resource  
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.Service.Backend.HPA.memoryUtilization }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 30
          periodSeconds: 60
---
{{- end -}}
