apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.RBAC.roleBinding }}
  namespace: {{ .Values.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.RBAC.serviceAccount }}
    namespace: {{ .Values.namespace }}
  - kind: Group
    name: {{ .Values.RBAC.group }} 
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .Values.RBAC.role }}
  apiGroup: rbac.authorization.k8s.io