name: Build and Push Docker Image to DigitalOcean

on:
  push:
    branches:
      - main  # Trigger on pushes to this branch  

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted runner with Ubuntu

    steps:
    - name: Set up Git to use PAT for authentication
      run: |
          git config --global url."https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/".insteadOf "https://github.com/"

    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository code


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

      # Cache Docker layers and BuildKit caches (local)
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ github.ref_name }}-
          ${{ runner.os }}-buildx-


    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest
        cache-from: |
          type=local,src=/tmp/.buildx-cache
          type=registry,ref=${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:build-cache
        cache-to: |
          type=registry,ref=${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:build-cache,mode=max
          type=local,dest=/tmp/.buildx-cache
        build-args: |
          VERSION=latest
        labels: |
          org.opencontainers.image.version=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.repository.updated_at }}

    - name: Logout from Docker
      run: docker logout ${{ secrets.DOCKER_REGISTRY }}

  build-and-push-backend:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted runner with Ubuntu

    steps:
    - name: Set up Git to use PAT for authentication
      run: |
          git config --global url."https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/".insteadOf "https://github.com/"

    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Create .env for backend
      run: |
        printf "%s" "${{ secrets.BACKEND_ENV }}" > ./backend/.env
        ls -la ./backend/.env 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ github.ref_name }}-
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest
        cache-from: |
          type=local,src=/tmp/.buildx-cache
          type=registry,ref=${{ secrets.DOCKER_USERNAME }}/portfolio-backend:build-cache
        cache-to: |
          type=registry,ref=${{ secrets.DOCKER_USERNAME }}/portfolio-backend:build-cache,mode=max
          type=local,dest=/tmp/.buildx-cache
        build-args: |
          VERSION=latest
        labels: |
          org.opencontainers.image.version=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.repository.updated_at }}

    - name: Logout from Docker
      run: docker logout ${{ secrets.DOCKER_REGISTRY }}
