name: Build and Push Docker Image to DigitalOcean

on:
  push:
    branches:
      - main  # Trigger on pushes to this branch  

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted runner with Ubuntu

    steps:
    - name: Set up Git to use PAT for authentication
      run: |
          git config --global url."https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/".insteadOf "https://github.com/"

    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository code


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest
        build-args: |
          VERSION=latest

    - name: Logout from Docker
      run: docker logout ${{ secrets.DOCKER_REGISTRY }}

  build-and-push-backend:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted runner with Ubuntu

    steps:
    - name: Set up Git to use PAT for authentication
      run: |
          git config --global url."https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/".insteadOf "https://github.com/"

    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Create .env for backend
      run: |
        printf "%s" "${{ secrets.BACKEND_ENV }}" > ./backend/.env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest
        build-args: |
          VERSION=latest

    - name: Logout from Docker
      run: docker logout ${{ secrets.DOCKER_REGISTRY }}
